export const ACCOUNT_SUMMARY_REQUEST = 'ACCOUNT::SUMMARY::REQUEST';
export const ACCOUNT_SUMMARY_REFRESH = 'ACCOUNT::SUMMARY::REFRESH';
export const ACCOUNT_TRANSACTIONS_REQUEST = 'ACCOUNT::TRANSACTIONS::REQUEST';
export const ACCOUNT_TRANSACTIONS_REFRESH = 'ACCOUNT::TRANSACTIONS::REFRESH';
export const ACCOUNT_FINANCIAL_REQUEST = 'ACCOUNT::FINANCIAL::REQUEST';
export const ACCOUNT_FINANCIAL_REFRESH = 'ACCOUNT::FINANCIAL::REFRESH';

export const LOGIN_REQUEST = 'LOGIN::REQUEST';
export const LOGIN_REFRESH = 'LOGIN::REFRESH';
export const LOGIN_FAILED = 'LOGIN::FAILED';

export const LOGOUT_REQUEST = 'LOGOUT::REQUEST';
export const LOGOUT_REFRESH = 'LOGOUT::REFRESH';

export const TOKEN_UNAUTHENTICATED = 'TOKEN::UNAUTHENTICATED';
export const TOKEN_REQUEST = 'TOKEN::REQUEST';
export const TOKEN_RECEIVED = 'TOKEN::RECEIVED';
export const TOKEN_FAILED = 'TOKEN::FAILED';
